package TestInstructionContainer_StandardSerialBaseContainer

import "github.com/jlambert68/FenixTestInstructionsAdminShared/TypeAndStructs"

const (
	TestInstructionContainerUUID_FenixStandard_StandardSerialBaseContainer TypeAndStructs.OriginalElementUUIDType = "e2b4b28d-5c59-4de8-bad3-001255c90466"
)
